### ISSUE TITLE
Scrolling not working on touchpad

### ISSUE THREAD

**Issue by lumberman** [dylanblokhuis/instantcss-wp#5]
Great plugin!
Unfortunately scrolling isn't functioning on touchpad on macbook.

**Comment by lumberman** [comment]
Look like fixed here: https://github.com/microsoft/vscode/commit/94702ffa04a201da20268a027dba597273522a97

**Comment by dylanblokhuis** [comment]
Thanks for the heads up, fixed in 1.1.3.

**Comment by lumberman** [comment]
Still not scrolling for me :(
Besides that have error in the console: https://d.pr/i/Z7zQu4

**Comment by dylanblokhuis** [comment]
Weird.. which browser + version on macbook?

**Comment by lumberman** [comment]
Firefox on MacBook Pro.

Problem solved after I forked the repo did npm install and update. Not sure if there is something to do with build process.

**Comment by unfresco** [comment]
Updating to monaco-editor v0.18.1+ should solve this [closed issue here](https://github.com/Microsoft/monaco-editor/issues/1353), @lumberman this is why your solution works. Can we expect this to be pushed to the wp.org repo in the next release? Great plugin, thanks!

**Comment by dylanblokhuis** [comment]
I might've fixed this a while ago, is this issue still occurring?

**Comment by dylanblokhuis** [comment]
Oh wait nevermind, that was a fix for firefox on windows

**Comment by dylanblokhuis** [comment]
Upgrade monaco to the latest version 0.20.0, which should fix all the issues.
